### ISSUE TITLE
Advanced Texture Extraction

### ISSUE THREAD

**Issue by Cosmas47** [tobywf/mech3ax-py#10]
## Which area of the project is your feature request related to?
CLI or mech3_from_zbd

## Detailed Description
I've observed on some texture ZBD files (non-MW3) that you may encounter a failure which stops all execution on the current textures#.zbd file. It may be useful to have either:

1. The ability to skip that file and attempt to continue processing the rest of the ZBD.
2. Separate the extraction and conversion commands for textures entirely.

**Comment by tobywf** [comment]
I'd definitely be interested in eventually looking at other Zipper file games, to see if I can fill in any gaps. Or a PR?

You'll get more out of this project if you treat it like a library (it didn't have a CLI until very recently, kinda to avoid me having to maintain it). You can create custom scripts that import `mech3ax` (see [`test.py`](https://github.com/tobywf/mech3ax/blob/master/test.py)) and run them with `poetry run python foo.py`, or just do `poetry run ipython` and do it all interactively. I should say that the APIs aren't stable though, I do plan on some smaller changes with the insights from progress on the remaining files.

You could start with something like `read_textures`, without all the logging or validation. There's a small annoyance that the texture table doesn't store the length of the data, so that needs to be worked out from other entries if you want to dump them without parsing them. Then you can run the conversion on each file via `_read_texture` (just pass in the individual file-data with offset 0).

**Comment by tobywf** [comment]
Did you have any luck? Something like this should do it:

```python
from mech3ax.parse.textures import TEX_HEADER, TEX_ENTRY
from mech3ax.parse.utils import ascii_zterm

data = open("texture.zbd", "rb").read()
count = TEX_HEADER.unpack_from(data, 0)[3]
offset = TEX_HEADER.size
table = []
for _ in range(count):
    name, start, _ = TEX_ENTRY.unpack_from(data, offset)
    offset += TEX_ENTRY.size
    name = ascii_zterm(name)
    table.append((name, start))

# to figure out the length, it easiest to start from the end of the file
table.sort(key=lambda v: v[1], reverse=True)
end = len(data)
for name, start in table:
    with open(f"{name}.bin", "wb") as f:
        f.write(data[start:end])
    end = start
```

**Comment by Cosmas47** [comment]
I know C# well but not Python so I stumbled through this but figured out a loop to get the files extracted.
It's when I need to get to converting them into PNGs where things go wrong. I started with:
```python
class Extraction:
	def convert_textures(self, base_path: Path) -> None:
		print("--- Converting Textures ---")
		do_stretch: bool = False
		fileList = os.listdir(base_path)
		textures = []
		for i in fileList:
			filePath = Path(base_path + i)
			data = filePath.read_bytes()
			print('Next File: ' + i)
			for texture in read_textures(data, do_stretch=do_stretch):
				#texture = _read_texture(data, i, 0, do_stretch=do_stretch)
				#TextureInfo.update_forward_refs()
				texture.image.save(i +'.png', format="png")
				info = TextureInfo(
					name=texture.name,
					mode=texture.image.mode,
					flags=TextureFlagExpander.from_flag(texture.flag),
					stretch=texture.stretch,
					palette_count=texture.palette_count,
					palette_data=texture.palette_data,
				)
				textures.append(info)
```
My output looks like this:
```
C:\Python38-32\Scripts\mech3ax>python convertTextures.py
--- Converting Textures ---
Next File: 00bbomber_logo1
Traceback (most recent call last):
  File "convertTextures.py", line 169, in <module>
    main()
  File "convertTextures.py", line 166, in main
    tester.convert_textures('C:/Python38-32/Scripts/mech3ax/textures/')
  File "convertTextures.py", line 96, in convert_textures
    for texture in read_textures(data, do_stretch=do_stretch):
  File "C:\Python38-32\Lib\site-packages\mech3ax\parse\textures.py", line 230, in read_textures
    assert_eq("field 1", 0, zero1, 0)
  File "C:\Python38-32\Lib\site-packages\mech3ax\errors.py", line 38, in assert_eq
    raise error_class(
mech3ax.errors.Mech3ParseError: Expected field 1 to be 0, but was 171 (at 0)

C:\Python38-32\Scripts\mech3ax>
```
Bear in mind, I'm working with Crimson Skies ZBD files, so I can only suspect there's some delta either between the MW3 archive or the image data. At one point I was able to extract the first file perfectly but it still error-ed before hitting the second, though I don't know what I did differently, I was at it all night.

Side notes, [watto's Game Extractor tool](http://www.watto.org/game_extractor.html) actually will read the audio and some of the texture zbd files. I suspect this may also work for MW3 and speaking of MW3 the tool [Texman ](http://trendsettasmechs.tripod.com/id4.htm) still works in a WinXP VM, though its hardcoded (in VB) to look for MW3 files only. 

Still.. this approach is more fun.

**Comment by tobywf** [comment]
so i have a few versions of MW3, and i put in some pretty strict assertions, to make it easier to detect issues/unexpected values (especially if i ever get around to the MW3 expansion). in all versions i have, that field is 0, and i haven't found it used in the executable yet. one solution is to comment out the assertions and see how far you get (you can just edit `C:\Python38-32\Lib\site-packages\mech3ax\parse\textures.py`, the beauty of Python).

unfortunately, the texture "archive" has no signature and no version, like some of the other files do, which would easily let us figure out if it's compatible. the other thing you can do it look at the files in a hex editor. in MW3, the file header is 24 bytes, and then there's the table with strings, which are very obvious (`demologo` and `demologo2` here):

```
$ hexdump -n 96 -C ~/Dropbox/mw3/install/v1.0-us-pre/zbd/rimage.zbd
00000000  00 00 00 00 01 00 00 00  00 00 00 00 8a 01 00 00  |................|
00000010  00 00 00 00 00 00 00 00  64 65 6d 6f 6c 6f 67 6f  |........demologo|
00000020  31 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |1...............|
00000030  00 00 00 00 00 00 00 00  a8 3d 00 00 ff ff ff ff  |.........=......|
00000040  64 65 6d 6f 6c 6f 67 6f  32 00 00 00 00 00 00 00  |demologo2.......|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

if your files have similar offsets, it might work. if not, it isn't worth trying, although it might be possible to figure out what the header looks like from the hexdump and go from there. (i've reached out via your website if you prefer email to continue the investigation!)

**Comment by tobywf** [comment]
so i have a few versions of MW3, and i put in some pretty strict assertions, to make it easier to detect issues/unexpected values (especially if i ever get around to the MW3 expansion). in all versions i have, that field is 0, and i haven't found it used in the executable yet. one solution is to comment out the assertions and see how far you get (you can just edit `C:\Python38-32\Lib\site-packages\mech3ax\parse\textures.py`, the beauty of Python).

unfortunately, the texture "archive" has no signature and no version, like some of the other files do, which would easily let us figure out if it's compatible. the other thing you can do it look at the files in a hex editor. in MW3, the file header is 24 bytes, and then there's the table with strings, which are very obvious (`demologo` and `demologo2` here):

```
$ hexdump -n 96 -C "zbd/rimage.zbd"
00000000  00 00 00 00 01 00 00 00  00 00 00 00 8a 01 00 00  |................|
00000010  00 00 00 00 00 00 00 00  64 65 6d 6f 6c 6f 67 6f  |........demologo|
00000020  31 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |1...............|
00000030  00 00 00 00 00 00 00 00  a8 3d 00 00 ff ff ff ff  |.........=......|
00000040  64 65 6d 6f 6c 6f 67 6f  32 00 00 00 00 00 00 00  |demologo2.......|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

if your files have the same offsets, it might work. if not, it isn't worth trying, although it might be possible to figure out what the header looks like from the hexdump and go from there. (i've reached out via your website if you prefer email to continue the investigation!)
