### ISSUE TITLE
Cockpit windows need a texture

### ISSUE THREAD

**Issue by tobywf** [tobywf/mech3ax-py#3]
## Which area of the project is your feature request related to?

Some materials don't have texture names, and the material data isn't well-enough understood to extract material properties. So once the models are exported to Blender, the cockpit windows don't have a texture or material properties and just appear grey.

### Hack around it

Two options: Can if part name == `head`, then apply cockpit material. Or, the unnamed materials are known, so could manually have workarounds for them in the script.

### Figure out the material data

So far, I haven't been able to find where the material data is loaded or used, because COM/DirectX is full of C++ classes which virtual tables and other indirection. More reverse engineering is needed, or maybe somebody from the community knows.

**Comment by tobywf** [comment]
Actually, the 'mechs render beautifully if this component is deleted or hidden. It might be used by the game, but less of an issue now

**Comment by AncientxFreako** [comment]
I can get you the cockpit textures if you want to try to use them. They exist in the rtexture.zbd file for each world.

**Comment by tobywf** [comment]
It's a good point, it's very possible these material names don't have textures because they're per-world (possibly for weather or other environmental effects, like the footprints do). In this case, it's just a flat polygon I think, that's more like a window than full cockpit geometry (which I assume is a different model, only rendered for the cockpit view mode). I did find `cpit_window.png`, which has transparency - maybe applying that is enough, without understanding more about the other material properties, although I assumed it needed some kind of alpha.

**Comment by tobywf** [comment]
We now understand some more material fields, and suspect one is alpha. Maybe this solves it.
